### PR TITLE
Added description to multiple cheats

### PR DESCRIPTION
**Pull request by Astr0nii**
Added a description to Omniaim in the pastes and scams section based on my knowledge and experience with the cheat.

### CODE REVIEW

**Review by Astr0nii — COMMENTED** [review]
Finished, if there's anything I missed or wrong about this list just tell me 👍

**Comment by danielchim** [comment]
What is a JME paste? Any links to it?

**Comment by Astr0nii** [comment]
> What is a JME paste? Any links to it?

Jme was a paster

**Comment by danielchim** [comment]
I see tho.

**Pull request merged**
